cmd/gopeed/main.go

Hi there, seem like you forgot to remove the test args.

Remove test args

---

ui/flutter/lib/api/api.dart
ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

according to https://github.com/cfug/dio/issues/1868, upgrading dio version to fixed.

fix: dio timeout don't throw exception

---

go.mod
internal/protocol/bt/fetcher.go
internal/protocol/bt/file.go
internal/protocol/bt/file_misc.go
internal/protocol/bt/file_piece.go

Improve torrent task creation speed.

feat: bt fetcher reuse

---

ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

fixed https://github.com/GopeedLab/gopeed/issues/161.

fix: file_picker crash on windows

---

go.mod
go.sum

fixed https://github.com/GopeedLab/gopeed/issues/159.

fix: bt file real time speed

---

go.mod
go.sum

related: https://github.com/GopeedLab/gopeed/issues/177

fix: go install fail

---

internal/protocol/http/fetcher.go
pkg/download/downloader.go

related: https://github.com/GopeedLab/gopeed/issues/185

fix: http download timeout

---

ui/flutter/pubspec.yaml

related: https://github.com/GopeedLab/gopeed/issues/175

fix: drop file crash on Windows

---

ui/flutter/lib/app/modules/create/views/create_view.dart

related: https://github.com/GopeedLab/gopeed/issues/174

feat: adjust size of resource dialog

---

go.mod
go.sum

related: https://github.com/GopeedLab/gopeed/issues/190

feat: adapts to Android 14

---

ui/flutter/lib/app/modules/create/controllers/create_controller.dart
ui/flutter/lib/app/modules/create/views/create_view.dart

When type or paste magnet hash, we will auto recognize and add `magnet:` prefix.

feat: auto recognize magnet uri

---

.github/workflows/build.yml

related: https://github.com/GopeedLab/gopeed/issues/228

feat: support arm/v6 and arm/v7 on docker

---

ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/lib/util/util.dart

related: https://github.com/GopeedLab/gopeed/issues/241

fix: linux system tray tooltip

---

cmd/gopeed/main.go
internal/protocol/bt/fetcher.go
pkg/download/downloader.go

related: https://github.com/GopeedLab/gopeed/issues/253

fix: gopeed cli BT download

---

internal/controller/controller.go
internal/protocol/bt/config.go
internal/protocol/bt/fetcher.go
internal/protocol/bt/fetcher_test.go
internal/protocol/http/config.go
internal/protocol/http/fetcher.go
internal/protocol/http/fetcher_test.go
pkg/base/constants.go
pkg/download/downloader.go
pkg/download/downloader_test.go
ui/flutter/lib/api/model/downloader_config.dart
ui/flutter/lib/api/model/downloader_config.g.dart
ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/lib/app/modules/setting/views/setting_view.dart

1. Support HTTP UA config (https://github.com/GopeedLab/gopeed/issues/276)
2. Support torrent listen port config https://github.com/GopeedLab/gopeed/issues/272

feat: support more configurations

---

pkg/download/downloader.go
pkg/download/engine/engine.go
pkg/download/engine/engine_test.go
pkg/download/engine/inject/error/module.go
pkg/download/engine/inject/util.go
pkg/download/engine/inject/xhr/module.go
pkg/download/engine/util/util.go
pkg/download/extension.go
pkg/download/extension_test.go
pkg/download/testdata/extensions/function_error/index.js
pkg/download/testdata/extensions/message_error/index.js
pkg/download/testdata/extensions/message_error/manifest.json
pkg/download/testdata/extensions/on_error/index.js
pkg/download/testdata/extensions/on_error/manifest.json
pkg/download/testdata/extensions/on_start/index.js
pkg/rest/server_test.go

1. support onError event
2. add built-in MessageError

feat: improve extension engine

---

Dockerfile
README.md
README_ja-JP.md
README_zh-CN.md
README_zh-TW.md
cmd/web/main.go
docker-compose.yml

related: https://github.com/GopeedLab/gopeed/issues/288

feat: support volume storage directory on docker

---

internal/protocol/http/fetcher.go
pkg/base/constants.go

https://github.com/GopeedLab/gopeed/issues/321
good night~

fix: compatible with not follow the http range response standard 

---

ui/flutter/lib/app/modules/setting/views/setting_view.dart
ui/flutter/lib/i18n/langs/en_us.dart
ui/flutter/lib/i18n/langs/zh_cn.dart
ui/flutter/lib/i18n/langs/zh_tw.dart

related: https://github.com/GopeedLab/gopeed/issues/326

fix: proxy setting only numeric input

---

pkg/download/downloader.go
pkg/protocol/http/model.go
ui/flutter/lib/api/model/options.dart
ui/flutter/lib/api/model/options.g.dart
ui/flutter/lib/app/modules/create/views/create_view.dart

related: https://github.com/GopeedLab/gopeed/issues/318

feat: auto create torrent task for http download

---

pkg/download/downloader.go
pkg/rest/api.go
pkg/rest/server.go
pkg/rest/server_test.go

related: https://github.com/GopeedLab/gopeed/issues/315

feat: add batch delete tasks api

---

pkg/util/bytefmt.go

看代码发现了一个小问题，这里是不是漏了 pb，从小到大然后才是 eb

fix: missing pb size format

---

README_zh-CN.md

docs: update README_zh-CN.md

---

ui/flutter/android/app/src/main/AndroidManifest.xml
ui/flutter/lib/app/modules/app/controllers/app_controller.dart

feat: Support Via Download task, require via version 5.5.0 or above (#412)

feat: Support Via Download task, require via version 5.5.0 or above (#412)

---

cmd/web/flags.go
cmd/web/main.go

related: https://github.com/GopeedLab/gopeed/issues/401

feat: web config add stroage dir

---

ui/flutter/android/app/src/main/AndroidManifest.xml

fix: Fix the issue of installing apk files(Android) (#448)

fix: Fix the issue of installing apk files(Android) (#448)

---

.github/workflows/build.yml

build linux with ubuntu latest

---

internal/protocol/http/fetcher.go

related: https://github.com/GopeedLab/gopeed/issues/488

fix: http request cookie incremented indefinitely on retries

---

pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/download/storage.go
pkg/rest/api.go
pkg/rest/model/action.go
pkg/rest/model/task.go
pkg/rest/server.go
pkg/rest/server_test.go

related: https://github.com/GopeedLab/gopeed/issues/500#issuecomment-2102400746

feat: add batch create and server info APIs

---

ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/lib/app/modules/setting/views/setting_view.dart
ui/flutter/lib/app/views/directory_selector.dart
ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

related: https://github.com/GopeedLab/gopeed/issues/493

feat: improve Android download directory choose

---

ui/flutter/lib/api/model/downloader_config.dart
ui/flutter/lib/api/model/downloader_config.g.dart
ui/flutter/lib/api/model/options.g.dart
ui/flutter/lib/api/model/resource.g.dart
ui/flutter/lib/api/model/result.g.dart
ui/flutter/lib/api/model/task.g.dart
ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/lib/app/modules/create/views/create_view.dart
ui/flutter/lib/app/views/buid_task_list_view.dart
ui/flutter/lib/app/views/compact_checkbox.dart
ui/flutter/lib/core/common/start_config.g.dart

related: https://github.com/GopeedLab/gopeed/issues/506

feat: remember delete task option

---

ui/flutter/lib/i18n/langs/pl_pl.dart

Corrections of translation errors.

feat: Update pl_pl.dart

---

README.md
README_ja-JP.md
README_vi-VN.md
README_zh-CN.md
README_zh-TW.md
internal/protocol/http/fetcher.go
ui/flutter/lib/app/modules/create/views/create_view.dart

related: https://github.com/GopeedLab/gopeed/issues/615

fix: handle empty string params

---

pkg/download/downloader.go

related: https://github.com/GopeedLab/gopeed/issues/845

fix: failed to delete a running task

---

ui/flutter/lib/app/modules/task/views/task_files_view.dart
ui/flutter/lib/app/views/buid_task_list_view.dart
ui/flutter/lib/app/views/file_icon.dart
ui/flutter/lib/app/views/file_tree_view.dart
ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

Improved interactive experience on mobile

feat: file tree view responsive support

---

ui/flutter/lib/api/model/downloader_config.g.dart
ui/flutter/lib/api/model/options.dart
ui/flutter/lib/api/model/options.g.dart
ui/flutter/lib/api/model/request.dart
ui/flutter/lib/api/model/request.g.dart
ui/flutter/lib/api/model/result.g.dart
ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/lib/app/modules/create/dto/create_router_params.dart
ui/flutter/lib/app/modules/create/dto/create_router_params.g.dart
ui/flutter/lib/app/modules/create/views/create_view.dart
ui/flutter/lib/app/modules/redirect/views/redirect_view.dart
ui/flutter/lib/app/routes/app_pages.dart
ui/flutter/lib/core/common/start_config.g.dart
ui/flutter/lib/util/scheme_register/entry/scheme_register_native.dart
ui/flutter/pubspec.yaml

Support for waking the downloader for create a task via the `gopeed://` protocol.

feat: support creating tasks using gopeed scheme

---

ui/flutter/ios/Podfile
ui/flutter/ios/Runner.xcodeproj/project.pbxproj
ui/flutter/ios/Runner/Info.plist
ui/flutter/ios/Runner/Runner.entitlements
ui/flutter/ios/ShareExtension/Base.lproj/MainInterface.storyboard
ui/flutter/ios/ShareExtension/Info.plist
ui/flutter/ios/ShareExtension/ShareExtension.entitlements
ui/flutter/ios/ShareExtension/ShareViewController.swift
ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

related: https://github.com/GopeedLab/gopeed/issues/880

fix: handle share links

---

ui/flutter/lib/app/modules/app/controllers/app_controller.dart

Fixes https://github.com/GopeedLab/gopeed/issues/941

fix: can not open url encode torrent file path

---

pkg/base/model.go
pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/rest/api.go
pkg/rest/model/task.go
pkg/rest/server_test.go
ui/flutter/lib/api/api.dart
ui/flutter/lib/api/model/create_task_batch.dart
ui/flutter/lib/api/model/create_task_batch.g.dart
ui/flutter/lib/app/modules/create/views/create_view.dart

fix: https://github.com/GopeedLab/gopeed/issues/977

feat: use batch download api for create multitasks

---

ui/flutter/lib/api/api.dart
ui/flutter/pubspec.yaml
ui/flutter/web/index.html

Fixed: https://github.com/GopeedLab/gopeed/issues/1000

feat: web support relative base path

---

.github/workflows/test.yml
cmd/web/flags.go
cmd/web/flags_test.go
cmd/web/main.go
pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/download/model.go
pkg/rest/server.go

Fixed: https://github.com/GopeedLab/gopeed/issues/1079

feat: add environment variables configuration support

---

ui/flutter/lib/app/modules/app/controllers/app_controller.dart
ui/flutter/pubspec.lock
ui/flutter/pubspec.yaml

Fixed: https://github.com/GopeedLab/gopeed/issues/549

fix: windows tray disappearing after sleep/wake cycles

---

internal/protocol/bt/file.go

Fixed: https://github.com/GopeedLab/gopeed/issues/1021

fix: resolve incorrect download path for single file torrent

---

pkg/rest/server.go

Fixed: https://github.com/GopeedLab/gopeed/issues/1105

fix: add timeout to server shutdown
