- .github/workflows/build.yml
- Dockerfile
Currently, gopeed is built in canvas mode, which depends on external resources, such as canvasKit.js and font files and css files. If the user’s network environment is not good, it will cause the page font not show. so now it is changed to html mode to build, 
there is no external resource dependency, and there is no problem in an environment without internet.
> feat: improve web build

- cmd/web/flags.go
- cmd/web/main.go
- pkg/rest/model/server.go
- pkg/rest/server.go
- pkg/rest/server_test.go
related: https://github.com/GopeedLab/gopeed/issues/146 https://github.com/GopeedLab/gopeed/issues/128 https://github.com/GopeedLab/gopeed/issues/117
> feat: web support http basic authorization

- pkg/download/downloader.go
Hello, monkeyWie, I'm dc
The modifications regarding https://github.com/GopeedLab/gopeed/issues/176 have been completed.
Using sync.Map would modify the important data structure of Download. The methods involve numerous load operations that require parameters of type any. Retrieving data also requires type checking of the load result, making the code rather cumbersome.
Considering that our primary focus is on the client-side program, simply using sync.RWMutex for locking is sufficient. Even if the server-side is involved, the download methods won't exhibit significant concurrency, and the locking scope is limited to the single write operation of storing data in the map. Therefore, the changes are straightforward.
Lately, I've been studying more about P2P-related aspects. In the upcoming …
> fix:current writes map

- .github/workflows/build.yml
- The version key does not represent the version of the application, but rather the version of the desktop entry specification that the file follows. The version field is not required. 
- The GenericName key is the generic name of the application, such as "Web Browser". 
- If the Icon key is an absolute path, the given file will be used. If the path is not an absolute path, it should not have a suffix. 
- Flutter_to_debian adds another Exec and Icon properties to the .desktop file even if there are already Exec and Icon. 
- By the way: If it seems more standardized for the application's parent directory to use the default /opt than /usr/local/bin, you can use postinst to link /opt/gopeed/gopeed to /usr/bin/gopeed. Flutter_to_debian supports postinst.
> ci: fix deb desktop entry

- internal/protocol/http/fetcher_test.go
- internal/test/httptest.go
- pkg/download/downloader.go
related: https://github.com/GopeedLab/gopeed/issues/275
> fix: task can not completed

- entrypoint.sh
忘了设置软件数据的权限了，刚刚发现如果设置权限为1000，docker容器无法启动
> fix: entrypoint_sh

- README.md
Fix filename discrepancies for .deb and .AppImage.
> docs: fix Linux download links

- internal/test/httptest.go
- pkg/base/model.go
- pkg/download/downloader.go
- pkg/download/downloader_test.go
- pkg/rest/server.go
- pkg/rest/server_test.go
related: https://github.com/GopeedLab/gopeed/issues/609
> fix: batch create tasks with duplicate names

- cmd/server.go
- cmd/web/flags.go
- cmd/web/main.go
- pkg/base/model.go
- pkg/base/model_test.go
- pkg/rest/model/server.go
- ui/flutter/lib/app/modules/setting/views/setting_view.dart
related: https://github.com/GopeedLab/gopeed/issues/605
> fix: web config file not loaded when is relative path

- internal/protocol/bt/fetcher.go
- ui/flutter/lib/app/modules/create/views/create_view.dart
- ui/flutter/lib/app/modules/extension/views/extension_view.dart
- ui/flutter/lib/app/views/open_in_new.dart
related: https://github.com/GopeedLab/gopeed/issues/751
> fix: torrent stats panic

- pkg/base/error.go
- pkg/download/downloader.go
- pkg/download/downloader_test.go
- pkg/download/model.go
- pkg/rest/model/server.go
related: https://github.com/GopeedLab/gopeed/issues/598
> feat: support download directory white list

- pkg/base/model.go
related: https://github.com/GopeedLab/gopeed/issues/800
> fix: proxy config reload panic

- Dockerfile
- docker-compose.yml
实测构建下来镜像缩小了大约5MB，升级了基础镜像alpine版本，给docker-compose优化了顺序，增加了一些选项[
](url)
> feat: optimize docker build

- .github/workflows/build.yml
* 打包过程中会下载两个包, 其中
* ~~***[qbuild_2.3.13.tar.gz](https://github.com/WHJWNAVY/QpkgBuildTools/releases/download/qbuild_2.3.13/qbuild_2.3.13.tar.gz)*** 为威联通平台安装包打包工具~~
* ***[qdk2_0.32.bionic_amd64.deb](https://github.com/qnap-dev/qdk2/releases/download/v0.32/qdk2_0.32.bionic_amd64.deb)*** 为威联通官方安装包打包工具
* ***[Gopeed.template.tar.gz](https://github.com/WHJWNAVY/QpkgBuildTools/releases/download/qbuild_2.3.13/Gopeed.template.tar.gz)*** 为 ***`qbuild`*** 工具打包时需要模板
* 目前这两个文件是放在我自己仓库中的，建议作者将这两个文件放到自己仓库中, 避免后期我删除了该仓库(`可能性很小`)后导致打包失败
* 暂时只打包了 ***`x86_64`*** 和 ***`arm_64`*** 两个平台的威联通安装包
> feat:  add QNAP platform build

- internal/protocol/http/fetcher.go
- pkg/download/extension.go
related: https://github.com/GopeedLab/gopeed/issues/831
> fix: extension modifed the request header cause HTTP fetch crash

- ui/flutter/lib/app/modules/app/views/app_view.dart
修复在Windows系统下切换明暗模式时，标题栏颜色没有切换的问题。
Fix the problem that the title bar color does not switch when switching between light and dark modes under Windows.
for issue ： https://github.com/GopeedLab/gopeed/issues/838
> fix: windows title bar theme switch

- internal/protocol/http/fetcher.go
> feat: improve http download retry strategy

- .github/workflows/build.yml
- pkg/rest/gizp_middleware.go
- pkg/rest/server.go
- pkg/rest/server_test.go
resolve: https://github.com/GopeedLab/gopeed/issues/957
> feat: web http file server caching and gzip support

- pkg/rest/server.go
- pkg/rest/server_test.go
fix: https://github.com/GopeedLab/gopeed/issues/958
> fix: web auth priority when api token and basic auth coexist

- ui/flutter/lib/util/util.dart
Fixed: https://github.com/GopeedLab/gopeed/issues/1044
This PR includes breaking changes because it has moved the persistent directories. If need to keep the old data,  you will need to manually move the `gopeed.db`, `database.hive`, `database.lock` files, and the `extensions folder`  from the application's main directory to the `./storage` directory.
> feat: update storage directory path for Windows
